### PR TITLE
Add support for legacy bucket

### PR DESCRIPTION
**Pull request by DanielMSchmidt**
:trollface:

### CODE REVIEW

**Comment by gluons** [comment]
I think you should save an image and put it in this repo instead of hotlink. 😀

**Review by DiegoRBaquero — APPROVED** [review]
We need backwards compat.

**Review by azz — CHANGES_REQUESTED** [review]
This is out of scope.

**Comment by DanielMSchmidt** [comment]
@azz is right, this might be out of scope

**Pull request closed without merging**
